### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by odow** [JuliaOpt/LinQuadOptInterface.jl#8]
These should all be covered by unit tests in MOIT.

### TODOs
- [x] get ConstraintSet of a `ScalarAffineFunction`-in`Interval` constraint.
- [x] get ConstraintSet of a `ScalarQuadraticFunction` constraint.
- [x] get ConstraintFunction of a `ScalarQuadraticFunction` constraint.
- [x] delete `ScalarQuadraticFunction` constraint.

### Objective
- [x] get quadratic function
- [x] <s>modify quadratic function?</s> Not MOI
- [x] single variable

### Variables
 - [ ] Basis stuff?

### Constraints
- [ ] modify  https://github.com/JuliaOpt/MathOptInterface.jl/issues/360
- [ ] transform
- [x] Stop shifting constants around https://github.com/JuliaOpt/MathOptInterface.jl/pull/358#discussion_r188128272

**Comment by joaquimg** [comment]
I think we can leave basis stuff for later.
Same for modifying quadratic objective (just delete and add a new one for now).

Once #23 is merged we only need to decide about:
- modify
- transform
